name: Windows build with Conan and custom batch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows-msvc:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Run Windows build script
        run: call build_win.bat release default
