name: Windows build with Conan and custom batch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows-msvc:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Detect Conan profile
        shell: pwsh
        run: |
          conan profile detect --force
          $profilePath = conan profile path default
          (Get-Content $profilePath) -replace 'compiler\.cppstd=\d+', 'compiler.cppstd=20' | Set-Content $profilePath
          Write-Host "Updated profile:"
          Get-Content $profilePath
          
      - name: Run Windows build script
        run: build_win.bat release default
        shell: cmd
